import {
  AppstoreOutlined,
  CalendarOutlined,
  CameraOutlined,
  CloseCircleOutlined,
  CopyOutlined,
  DollarOutlined,
  EditOutlined,
  FacebookOutlined,
  FileImageOutlined,
  FolderAddOutlined,
  FolderOutlined,
  FormOutlined,
  HomeOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LayoutOutlined,
  LinkOutlined,
  MailOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  PaperClipOutlined,
  PhoneOutlined,
  PictureOutlined,
  PieChartOutlined,
  PlusCircleOutlined,
  RocketOutlined,
  SelectOutlined,
  SettingOutlined,
  SolutionOutlined,
  StarOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  UserOutlined,
  UsergroupAddOutlined,
  VideoCameraOutlined,
  WechatOutlined,
} from "@ant-design/icons";

function getItem(label, key, icon, children, type) {
  return {
    key,
    icon,
    children,
    label,
    type,
  };
}
export const items = [
  getItem("Quản Lý Chung", "/home", <HomeOutlined />),
  getItem("Cấu hình", "/home/information", <SettingOutlined />, [
    getItem("Cấu hình chung", "/home/information", <SettingOutlined />),
    getItem("Quản lý file", "settingfile", <SettingOutlined />),
    getItem("Cài đặt ứng dụng", "/home/informationapp", <MenuUnfoldOutlined />),
    getItem("Tối ưu hóa tìm kiếm", "", <CopyOutlined />, [
      getItem("Cấu hình meta toàn trang", "/home/settingseo-meta",<SettingOutlined/>),
      getItem("SEO URL", "/home/settingseo",<KeyOutlined />),
      // getItem("Cài đặt dạng tên miền", "6"),
      // getItem("Google Authorship", "6"),
      // getItem("Quản lí file robot.txt", "6"),
      // getItem("Google analytics", "6"),
      // getItem("Google sitemap", "6"),
      // getItem("Quản lý tags", "6"),
    ]),
    getItem("Cài đặt chân trang", "/home/information-footer", <PaperClipOutlined />),
    getItem("Liên hệ", "10", <PhoneOutlined />, [
      getItem("Cài đặt trang liên hệ", "/home/contact-info",<PhoneOutlined/>),
      getItem("Quản lí liên hệ", "/home/contact-management",<PhoneOutlined/>),
    ]),
    getItem("Ý kiến khách hàng", "/home/customer-review", <WechatOutlined />, [
      getItem("Danh sách ý kiến KH", "/home/customer-review",<MenuOutlined/>),
      getItem("Cài đặt ý kiến khách hàng", "/home/setting-customer",<SettingOutlined/>),
    ]),
    getItem("Cài đặt tên miền", "/home/information-settingdomain", <SettingOutlined />),
    getItem("Cài đặt ngôn ngữ", "/home/information-lan", <SettingOutlined />),
    getItem("Cài đặt bản đồ", "/home/maps", <SettingOutlined />),
    getItem("Đăng kí bộ CT", "15", <SolutionOutlined />),
    getItem("Thành viên", "16", <UserOutlined />, [
      getItem("Quản lí thành viên", "1"),
    ]),
    getItem("Đóng Website", "17", <CloseCircleOutlined />),
  ]),
  getItem("Giao diện", "sub3", <StarOutlined />, [
    getItem("Cài đặt cơ bản", "9", <SettingOutlined />),
    getItem("Quản lí slide", "10", <PlusCircleOutlined />, [
      getItem("Đăng slide", "1", <PlusCircleOutlined />),
      getItem("Danh sách slide", "1", <MenuOutlined />),
      getItem("Đăng ảnh  slide", "1", <PlusCircleOutlined />),
      getItem("Danh sách ảnh slide", "1", <MenuOutlined />),
    ]),
    getItem("Quản lí block", "11", <FolderOutlined />, [
      getItem("Cài đặt block", "1", <SettingOutlined />),
      getItem("Block mạng xã hội ", "1", <FacebookOutlined />),
      getItem("Block hỗ trợ", "1", <PhoneOutlined />),
      getItem("Quản lí block tùy chỉnh", "1", <ToolOutlined />),
    ]),
    getItem("Quản lí trang chủ", "12", <HomeOutlined />),
    getItem("Cài đặt layout", "12", <LayoutOutlined />),
    getItem("Form tùy chỉnh", "12", <FormOutlined />, [
      getItem("Thêm form tùy chỉnh", "1", <PlusCircleOutlined />),
      getItem("Quản lí form tùy chỉnh", "1", <MenuUnfoldOutlined />),
    ]),
  ]),
  getItem("Giới thiệu", "sub4", <CopyOutlined />, [
    getItem("Đăng giới thiệu", "2", <PlusCircleOutlined />),
    getItem("Quản lí giới thiệu", "3", <MenuUnfoldOutlined />),
  ]),
  getItem("Trang chuyên mục", "sub5", <FormOutlined />, [
    getItem("Đăng chuyên mục", "2", <EditOutlined />),
    getItem("Danh sách chuyên mục", "3", <MenuUnfoldOutlined />),
  ]),
  getItem("Menu", "sub6", <MenuUnfoldOutlined />, [
    getItem("Quản lí menu trên", "2", <MenuUnfoldOutlined />),
    getItem("Quản lí menu dưới", "3", <MenuUnfoldOutlined />),
    getItem("Danh mục tùy chọn", "3", <MenuUnfoldOutlined />),
    getItem("Menu tùy chọn", "3", <MenuUnfoldOutlined />),
  ]),
  getItem("Sản phẩm", "/home/product", <CalendarOutlined />, [
    getItem("Đăng sản phẩm", "2", <PlusCircleOutlined />),
    getItem("Quản lí sản phẩm", "3", <AppstoreOutlined />),
    getItem("Danh mục sản phẩm", "4", <MenuUnfoldOutlined />),
    getItem("Tính năng", "5", <ThunderboltOutlined />),
    getItem("Bán hàng", "6", <DollarOutlined />),
    getItem("Quà tặng kèm", "7", <StarOutlined />),
    getItem("Đặc tính", "8", <PieChartOutlined />),
    getItem("Nâng cao", "9", <SelectOutlined />),
    // getItem("Kết nối Sendo", "10", <LinkOutlined />),
    // getItem("Kết nối lazada", "11", <LinkOutlined />),
    // getItem("Kết nối Bpos", "12", <LinkOutlined />),
  ]),
  getItem("Tin tức", "sub8", <CalendarOutlined />, [
    getItem("Đăng tin tức", "2", <PlusCircleOutlined />),
    getItem("Quản lí tin tức", "3", <MenuUnfoldOutlined />),
    getItem("Đăng danh mục", "4", <PlusCircleOutlined />),
    getItem("Danh mục tin tức", "5", <MenuOutlined />),
    getItem("Cài đặt tin tức", "6", <SettingOutlined />),
  ]),
  getItem("Album", "sub9",<PictureOutlined />, [
    getItem("Đăng album", "2", <PlusCircleOutlined />),
    getItem("Quản lí album", "3", <MenuUnfoldOutlined />),
    getItem("Đăng danh mục", "4", <PlusCircleOutlined />),
    getItem("Danh mục album", "5", <MenuUnfoldOutlined />),
    getItem("Cài đặt album", "6", <SettingOutlined />),
  ]),
  getItem("Video", "sub10",<VideoCameraOutlined />, [
    getItem("Đăng video", "2", <PlusCircleOutlined />),
    getItem("Danh sách video", "3", <MenuUnfoldOutlined />),
    getItem("Đăng danh mục video", "4", <PlusCircleOutlined />),
    getItem("Danh sách danh mục", "5", <MenuUnfoldOutlined />),
    getItem("Cài đặt video", "6", <SettingOutlined />),
  ]),
  getItem("Hỏi đáp", "sub11",<InfoCircleOutlined />, [
    getItem("Đăng danh mục hỏi đáp", "2", <PlusCircleOutlined />),
    getItem("Quản lí danh mục hỏi đáp", "3", <MenuUnfoldOutlined />),
    getItem("Quản lí câu hỏi", "4", <MenuUnfoldOutlined />),
    getItem("Quản lí câu hỏi phạm quy", "5", <MenuUnfoldOutlined />),
    getItem("Quản lí trả lời phạm quy", "6", <MenuUnfoldOutlined />),
    getItem("Cài đặt hỏi đáp", "6", <SettingOutlined />),
  ]),
  getItem("Tuyển dụng", "sub12",<UsergroupAddOutlined />, [
    getItem("Đăng tuyển dụng", "2", <PlusCircleOutlined />),
    getItem("Quản lí tuyển dụng", "3", <MenuUnfoldOutlined />),
    getItem("Quản lí hồ sơ gửi về", "5", <MenuUnfoldOutlined />),
    getItem("Cài đặt tuyển dụng", "6", <SettingOutlined />),
  ]),
  getItem("Quảng cáo", "sub13",<RocketOutlined />, [
    getItem("Đăng nhà quảng cáo", "2", <PlusCircleOutlined />),
    getItem("Nhà quảng cáo", "3", <StarOutlined />),
    getItem("Đăng quảng cáo", "5", <PlusCircleOutlined />),
    getItem("Quản lí quảng cáo", "6", <SettingOutlined />),
  ]),
  getItem("Quản lý tập tin", "sub14",<CameraOutlined />),
  getItem("Danh sách đăng kí nhận tin", "sub15",<MailOutlined />),
  getItem("Báo cáo", "sub16",<MenuUnfoldOutlined/>, [
    getItem("Báo cáo liên hệ", "2", <MenuUnfoldOutlined/>),
    getItem("Báo cáo ý kiến KH", "3", <MenuUnfoldOutlined/>),
  ]),
  getItem("Ứng dụng", "sub16",<AppstoreOutlined />),
];
